//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChatBotResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChatBotResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatBot.Resources.ChatBotResources", typeof(ChatBotResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Существующие файлы в репозитории:
        ///{0}. .
        /// </summary>
        internal static string DELETE_ATTACHMENT {
            get {
                return ResourceManager.GetString("DELETE_ATTACHMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я поддерживаю следующие команды:
        ///{0}
        ///Для того, чтобы узнать больше по каждой из них, напиши: help [command]..
        /// </summary>
        internal static string HELP_DESCRIPTION {
            get {
                return ResourceManager.GetString("HELP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, но такой комманды нет в списке. Введите &apos;help&apos; для справки..
        /// </summary>
        internal static string HELP_DIDNT_FIND_COMMAND {
            get {
                return ResourceManager.GetString("HELP_DIDNT_FIND_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для дополнительной информации введите предложение, содержащее help..
        /// </summary>
        internal static string HELP_MESSAGE {
            get {
                return ResourceManager.GetString("HELP_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет! Вы стали счастливым пользователем меня:) 
        ///Для дополнительной информации введите help..
        /// </summary>
        internal static string WELCOME_MESSAGE {
            get {
                return ResourceManager.GetString("WELCOME_MESSAGE", resourceCulture);
            }
        }
    }
}
